---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: msbridgekm-svc
  name: msbridgekm-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: msbridgekm-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: msbridgekm-svc
    spec:
      containers:
      - image: docker.io/morjuela/bridge_kaf_mqtt
        imagePullPolicy: IfNotPresent
        name: msbridgekm-svc
        ports:
        - containerPort: 1883
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: msbridgekm-svc
  name: msbridgekm-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1883
  selector:
    run: msbridgekm-svc
  sessionAffinity: None
  type: LoadBalancer