---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: msdirectoryc-svc
  name: msdirectoryc-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: msdirectoryc-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: msdirectoryc-svc
    spec:
      containers:
      - name: msdirectoryc-svc
        image: docker.io/morjuela/directoryc-microservice
        imagePullPolicy: IfNotPresent
        env:
        - name: API_QUEUE
          value: "172.31.3.25"
        ports:
        - containerPort: 3096
      - name: dbdirectoryc-svc
        image: docker.io/morjuela/directoryc-db
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: msdirectoryc-svc
  name: msdirectoryc-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3096
  selector:
    run: msdirectoryc-svc
  sessionAffinity: None
  type: LoadBalancer
